// 생성 대상 목록: 어떤 조각(template)에 어떤 값(vars)을 채워 payload의 어느 파일(out)을 만드는지 선언한다.
// 값 규칙은 scripts/generate-workflows.mjs 머리말 참고 — 문자열은 인라인 치환, 배열은 자리표시자 한 줄 전체를 대체한다.
//
// 이 파일이나 조각을 고쳤다면 `npm run generate:workflows`로 payload를 다시 만들고 함께 커밋한다.

// Go/Python PR 프리뷰가 공유하는 조각. 타입별로 다른 곳만 vars에 둔다.
const PR_PREVIEW = "pr-preview.base.yaml";

// React/Next 배포가 공유하는 조각. 컨테이너 실행 옵션·안내 주석 등 다른 곳만 vars에 둔다.
const CICD_FRONTEND = "cicd-frontend.base.yaml";

// Go/Python 단일 서버 배포(SSH + Docker)가 공유하는 조각. 타입별로 다른 곳만 vars에 둔다.
const SIMPLE_CICD = "simple-cicd.base.yaml";

export const TARGETS = [
  {
    out: "payload/workflows/go/PROJECT-GO-PR-PREVIEW.yaml",
    template: PR_PREVIEW,
    vars: {
      TYPE_UPPER: "GO",
      SUFFIX: "go",
      INTERNAL_PORT: "8080",
      HEADER_TITLE: [
        "# Go PR Preview (SSH + Docker + Traefik)",
        "# PR 또는 Issue 코멘트 명령어를 통해 Preview 환경을 자동으로 관리합니다. Traefik 리버스 프록시로 동적 라우팅됩니다.",
      ],
      HEADER_SECRETS: [
        "# DOCKERHUB_USERNAME / DOCKERHUB_TOKEN: Docker Hub 사용자명 / 액세스 토큰",
        "# SERVER_HOST / SERVER_USER: 서버 호스트(SSH 접속 주소) / SSH 사용자명",
      ],
      SETTINGS_TITLE: ["# [영역 1] 프로젝트별 설정 - 다른 프로젝트에서 사용 시 이 섹션만 수정하세요"],
      HEALTH_BLOCK: [
        "#   Go (net/http 등): '/health', 'listening on'",
        "HEALTH_CHECK_PATH: '/health'",
        "HEALTH_CHECK_LOG_PATTERN: 'listening on'",
        "API_DOCS_PATH: ''",
      ],
      BUILD_FAIL_HINTS: [
        "'- Docker 이미지 빌드 실패 (Go 의존성/빌드 문제)',",
        "'- 컨테이너 시작 실패 (애플리케이션 기동 오류)',",
      ],
      PR_CHECK_COMMENT: ["# PR인지 Issue인지 확인"],
      PARSE_COMMENT: ["# 명령어 파싱 (브랜치 파라미터 지원)"],
      SHA_COMMENT: ["# 브랜치의 최신 커밋 SHA 가져오기"],
      HEALTH_COMMENT: ["# Health Check"],
      ENV_OPEN: ["# [영역 2] 환경변수 파일 생성"],
      ENV_CLOSE: ["# [영역 2 끝] 환경변수 파일 생성 끝"],
    },
  },
  {
    out: "payload/workflows/python/PROJECT-PYTHON-PR-PREVIEW.yaml",
    template: PR_PREVIEW,
    vars: {
      TYPE_UPPER: "PYTHON",
      SUFFIX: "python",
      INTERNAL_PORT: "8000",
      HEADER_TITLE: [
        "# Python/FastAPI PR Preview (SSH + Docker + Traefik)",
        "# PR 또는 Issue 코멘트 명령어를 통해 Preview 환경을 자동으로 관리합니다.",
        "# Traefik 리버스 프록시를 통해 동적 라우팅됩니다.",
      ],
      HEADER_SECRETS: [
        "# DOCKERHUB_USERNAME: Docker Hub 사용자명",
        "# DOCKERHUB_TOKEN: Docker Hub 액세스 토큰",
        "# SERVER_HOST: 서버 호스트(SSH 접속 주소)",
        "# SERVER_USER: SSH 사용자명",
      ],
      SETTINGS_TITLE: ["# 프로젝트별 설정: 다른 프로젝트에서 사용 시 이 섹션만 수정하세요"],
      HEALTH_BLOCK: [
        "HEALTH_CHECK_PATH: '/docs'",
        "HEALTH_CHECK_LOG_PATTERN: 'Uvicorn running on|Application startup complete'",
        "API_DOCS_PATH: '/docs'",
      ],
      BUILD_FAIL_HINTS: [
        "'- Docker 이미지 빌드 실패 (Python 의존성 문제)',",
        "'- 컨테이너 시작 실패 (FastAPI/Uvicorn 기동 오류)',",
      ],
      // Python 쪽에는 없는 안내 주석이라 빈 배열로 줄 자체를 없앤다
      PR_CHECK_COMMENT: [],
      PARSE_COMMENT: [],
      SHA_COMMENT: [],
      HEALTH_COMMENT: [],
      ENV_OPEN: ["# 환경변수 파일 생성 (프로젝트별 수정 영역)"],
      ENV_CLOSE: [],
    },
  },
  {
    out: "payload/workflows/react/PROJECT-REACT-CICD.yaml",
    template: CICD_FRONTEND,
    vars: {
      TYPE_UPPER: "REACT",
      IMAGE_PREFIX: "front-container",
      BUILD_JOB_NAME: "React/Next.js 애플리케이션 빌드",
      PULL_MSG: ": ${{ secrets.DOCKERHUB_USERNAME }}/${PROJECT_NAME}-${{ env.DOCKER_IMAGE_PREFIX }}:${BRANCH}",
      HEADER: [
        "# React CI/CD 배포",
        "# {{MAIN_BRANCH}} 브랜치 푸시 시 Docker 이미지를 빌드하고 배포합니다.",
      ],
      DEPLOY_VARS: [
        "# GitHub에서 전달받은 브랜치명",
        "BRANCH=${{ github.ref_name }}",
        "",
        "# 프로젝트 설정",
        "PROJECT_NAME=\"${{ env.PROJECT_NAME }}\"",
        "",
        "# 브랜치별 포트 및 컨테이너명 설정",
        "# 기본값 설정",
        "PORT=3000",
        "CONTAINER_NAME=\"${PROJECT_NAME}-front\"",
      ],
      BRANCH_BLOCK: [
        "# 브랜치에 따른 환경별 설정",
        "if [ \"$BRANCH\" == \"{{MAIN_BRANCH}}\" ]; then",
        "  # 🚀 배포 환경 ({{MAIN_BRANCH}} 브랜치)",
        "  # GitHub Secrets의 PROJECT_DEPLOY_PORT 환경변수 사용",
        "  # 설정되어 있지 않으면 기본값 3000 사용",
        "  PORT=${{ secrets.PROJECT_DEPLOY_PORT || '3000' }}",
        "  CONTAINER_NAME=\"${PROJECT_NAME}-front-deploy\"",
        "  echo \"🚀 배포 환경으로 배포합니다 (브랜치: $BRANCH)\"",
        "",
        "else",
        "  # 기타 브랜치 (예상치 못한 브랜치)",
        "  echo \"⚠️ 지원하지 않는 브랜치입니다: $BRANCH\"",
        "  echo \"이 워크플로우는 {{MAIN_BRANCH}} 브랜치만 지원합니다.\"",
        "  echo \"on.push.branches에서 지원할 브랜치를 설정하세요.\"",
        "  exit 1",
        "fi",
      ],
      CONFIG_COMMENT: [
        "# 설정 정보 출력",
      ],
      EXISTING_COMMENT: [
        "# 동일한 이름의 컨테이너가 존재하는지 확인",
      ],
      RUN_COMMENT: [],
      RUN_ENV: [],
      RUN_RESTART: [],
      FOOTER: [
        "# 사용 예시 - {{MAIN_BRANCH}} 브랜치 사용",
        "#",
        "# 현재 설정: {{MAIN_BRANCH}} 브랜치에 push할 때 자동 배포",
        "#",
        "# 브랜치별 포트:",
        "# - {{MAIN_BRANCH}}: 3000 (PROJECT_DEPLOY_PORT secret으로 변경 가능)",
        "#",
        "# 필요한 Secrets:",
        "# - REACT_ENV_FILE, DOCKERHUB_*, SERVER_* (필수)",
        "# - PROJECT_DEPLOY_PORT (선택, 기본값: 3000)",
        "#",
        "",
      ],
    },
  },
  {
    out: "payload/workflows/next/PROJECT-NEXT-CICD.yaml",
    template: CICD_FRONTEND,
    vars: {
      TYPE_UPPER: "NEXT",
      IMAGE_PREFIX: "nextjs-container",
      BUILD_JOB_NAME: "Next.js 애플리케이션 빌드",
      PULL_MSG: "...",
      HEADER: [
        "# Next.js CI/CD 배포",
        "# {{MAIN_BRANCH}} 브랜치 푸시 시 Docker 이미지를 빌드하고 배포합니다. SSR 지원을 위해 Node.js 런타임 컨테이너로 배포됩니다.",
      ],
      DEPLOY_VARS: [
        "BRANCH=${{ github.ref_name }}",
        "PROJECT_NAME=\"${{ env.PROJECT_NAME }}\"",
        "",
        "# 브랜치별 포트 및 컨테이너명 설정",
        "PORT=3000",
        "CONTAINER_NAME=\"${PROJECT_NAME}-nextjs\"",
      ],
      BRANCH_BLOCK: [
        "if [ \"$BRANCH\" == \"{{MAIN_BRANCH}}\" ]; then",
        "  PORT=${{ secrets.PROJECT_DEPLOY_PORT || '3000' }}",
        "  CONTAINER_NAME=\"${PROJECT_NAME}-nextjs-deploy\"",
        "  echo \"🚀 배포 환경으로 배포합니다 (브랜치: $BRANCH)\"",
        "else",
        "  echo \"⚠️ 지원하지 않는 브랜치입니다: $BRANCH\"",
        "  exit 1",
        "fi",
      ],
      CONFIG_COMMENT: [],
      EXISTING_COMMENT: [],
      RUN_COMMENT: [
        "# Next.js는 SSR을 위해 Node.js 서버가 필요합니다",
        "# standalone 모드 사용 시 node server.js로 실행",
      ],
      RUN_ENV: [
        "-e NODE_ENV=production \\",
      ],
      RUN_RESTART: [
        "--restart unless-stopped \\",
      ],
      FOOTER: [
        "# Next.js Dockerfile 예시 (standalone 모드)",
        "#",
        "# # Stage 1: Dependencies",
        "# FROM node:20-alpine AS deps",
        "# WORKDIR /app",
        "# COPY package*.json ./",
        "# RUN npm ci --only=production",
        "#",
        "# # Stage 2: Builder",
        "# FROM node:20-alpine AS builder",
        "# WORKDIR /app",
        "# COPY --from=deps /app/node_modules ./node_modules",
        "# COPY . .",
        "# RUN npm run build",
        "#",
        "# # Stage 3: Runner",
        "# FROM node:20-alpine AS runner",
        "# WORKDIR /app",
        "# ENV NODE_ENV production",
        "#",
        "# RUN addgroup --system --gid 1001 nodejs",
        "# RUN adduser --system --uid 1001 nextjs",
        "#",
        "# COPY --from=builder /app/public ./public",
        "# COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./",
        "# COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static",
        "#",
        "# USER nextjs",
        "# EXPOSE 3000",
        "# ENV PORT 3000",
        "# CMD [\"node\", \"server.js\"]",
        "#",
        "# next.config.js에 standalone 설정 추가:",
        "# module.exports = {",
        "#   output: 'standalone',",
        "# }",
      ],
    },
  },
  {
    out: "payload/workflows/go/PROJECT-GO-SIMPLE-CICD.yaml",
    template: SIMPLE_CICD,
    vars: {
      TYPE_UPPER: "GO",
      SUFFIX: "go",
      DEPLOY_PORT_DEFAULT: "8080",
      HEADER_TITLE: ["# Go CI/CD 배포 (SSH + Docker)"],
      HEADER_SECRETS: [
        "# DOCKERHUB_USERNAME / DOCKERHUB_TOKEN: DockerHub 사용자명 / 액세스 토큰",
        "# SERVER_HOST / SERVER_USER: 배포 서버 주소 / SSH 사용자명",
      ],
      HEADER_ENV: [
        "# 환경변수 (env 섹션에서 설정)",
        "# CONTAINER_INTERNAL_PORT: Go 앱 내부 포트 (기본: 8080) / DEPLOY_PORT: 배포 포트",
        "# CONTAINER_NAME: 컨테이너 이름 (기본: PROJECT_NAME)",
        "# ENABLE_VOLUME_MOUNT (true/false), VOLUME_HOST_PATH, VOLUME_CONTAINER_PATH: 볼륨 마운트",
        "# SSH_PORT (기본: 2022), SSH_COMMAND_TIMEOUT (기본: 600s), SSH_CONNECTION_TIMEOUT (기본: 60s)",
        "# HEALTHCHECK_WAIT_SECONDS: 초기화 대기 시간 (기본: 10초)",
        "# HEALTHCHECK_PATH: HTTP 엔드포인트 경로 (비어있으면 로그만 사용, 예: \"/health\", \"/api/v1/health\")",
        "# HEALTHCHECK_MAX_RETRIES: HTTP 재시도 횟수 (기본: 5회) / HEALTHCHECK_RETRY_INTERVAL: 재시도 간격 (기본: 3초)",
        "# HEALTHCHECK_LOG_PATTERN: Fallback 로그 검색 패턴",
      ],
      PORT_COMMENT: [],
      SSH_COMMENT: [],
      CONTAINER_PORT_BLOCK: ["CONTAINER_INTERNAL_PORT: \"8080\"  # Go 앱 내부 포트"],
      HEALTH_PATH: "/health",
      HEALTH_LOG_LINE: [
        "HEALTHCHECK_LOG_PATTERN: \"listening on\"  # Fallback 로그 검색 패턴 (프로젝트 로그 문구에 맞게 조정)",
      ],
      BUILD_JOB_NAME: "Go 애플리케이션 빌드",
      PULL_SUFFIX: "",
      RUN_DOC: [
        "# - 포트 매핑: ${PORT}:${{ env.CONTAINER_INTERNAL_PORT }} (외부:내부)",
        "# - 시간대: Asia/Seoul",
        "# - 볼륨 마운트: 로컬 시간 동기화 및 프로젝트 데이터",
      ],
      VOLUME_COMMENT: ["# 볼륨 마운트 옵션 구성"],
      DONE_COMMENT: ["# 배포 완료 확인"],
      URL_SUFFIX: "",
    },
  },
  {
    out: "payload/workflows/python/PROJECT-PYTHON-SIMPLE-CICD.yaml",
    template: SIMPLE_CICD,
    vars: {
      TYPE_UPPER: "PYTHON",
      SUFFIX: "python",
      DEPLOY_PORT_DEFAULT: "8000",
      HEADER_TITLE: ["# Python FastAPI CI/CD 배포 (SSH + Docker)"],
      HEADER_SECRETS: [
        "# DOCKERHUB_USERNAME: DockerHub 사용자명",
        "# DOCKERHUB_TOKEN: DockerHub 액세스 토큰",
        "# SERVER_HOST: 배포 서버 주소",
        "# SERVER_USER: SSH 사용자명",
      ],
      HEADER_ENV: [
        "# 환경변수는 아래 env 섹션에서 설정하며, 항목별 설명과 기본값은 각 줄에 적혀 있습니다.",
        "# HEALTHCHECK_PATH 예시: FastAPI \"/docs\", 커스텀 \"/api/v1/health\"",
      ],
      PORT_COMMENT: ["# 포트 설정"],
      SSH_COMMENT: ["# SSH 연결 설정"],
      CONTAINER_PORT_BLOCK: [
        "# 컨테이너 포트 설정",
        "CONTAINER_INTERNAL_PORT: \"8000\"  # FastAPI 내부 포트",
      ],
      HEALTH_PATH: "/docs",
      HEALTH_LOG_LINE: ["HEALTHCHECK_LOG_PATTERN: \"Uvicorn running on\"  # Fallback 로그 검색 패턴"],
      BUILD_JOB_NAME: "Python FastAPI 애플리케이션 빌드",
      PULL_SUFFIX: " (Pull)",
      // Python 쪽에는 없는 안내 주석이라 빈 배열로 줄 자체를 없앤다
      RUN_DOC: [],
      VOLUME_COMMENT: [],
      DONE_COMMENT: [],
      URL_SUFFIX: "/docs",
    },
  },
];
