// Generation targets: declares which template gets which values (vars) to produce which payload file (out).
// For the value rules see the header of scripts/generate-workflows.mjs: a string is substituted inline,
// an array replaces the whole placeholder line.
//
// After editing this file or a template, run `npm run generate:workflows` and commit the regenerated payload with it.

// Template shared by the Go/Python PR previews. Only the per-type differences go into vars.
const PR_PREVIEW = "pr-preview.base.yaml";

// Template shared by the React/Next deployments. Only differences (container run options, guide comments, ...) go into vars.
const CICD_FRONTEND = "cicd-frontend.base.yaml";

// Template shared by the Go/Python single-server deployments (SSH + Docker). Only the per-type differences go into vars.
const SIMPLE_CICD = "simple-cicd.base.yaml";

export const TARGETS = [
  {
    out: "payload/workflows/go/PROJECT-GO-PR-PREVIEW.yaml",
    template: PR_PREVIEW,
    vars: {
      TYPE_UPPER: "GO",
      SUFFIX: "go",
      INTERNAL_PORT: "8080",
      HEADER_TITLE: [
        "# Go PR Preview (SSH + Docker + Traefik)",
        "# Manages the preview environment automatically through PR or issue comment commands. Routing is dynamic via the Traefik reverse proxy.",
      ],
      HEADER_SECRETS: [
        "# DOCKERHUB_USERNAME / DOCKERHUB_TOKEN: Docker Hub username / access token",
        "# SERVER_HOST / SERVER_USER: server host (SSH address) / SSH username",
      ],
      SETTINGS_TITLE: ["# [Section 1] Project settings - when reusing this in another project, edit only this section"],
      HEALTH_BLOCK: [
        "#   Go (net/http, etc.): '/health', 'listening on'",
        "HEALTH_CHECK_PATH: '/health'",
        "HEALTH_CHECK_LOG_PATTERN: 'listening on'",
        "API_DOCS_PATH: ''",
      ],
      BUILD_FAIL_HINTS: [
        "m('wf_preview.hint_docker_go'),",
        "m('wf_preview.hint_start_go'),",
      ],
      PR_CHECK_COMMENT: ["# Check whether this is a PR or an issue"],
      PARSE_COMMENT: ["# Parse the command (branch argument supported)"],
      SHA_COMMENT: ["# Get the latest commit SHA of the branch"],
      HEALTH_COMMENT: ["# Health Check"],
      ENV_OPEN: ["# [Section 2] Create the environment file"],
      ENV_CLOSE: ["# [End of section 2] Create the environment file"],
    },
  },
  {
    out: "payload/workflows/python/PROJECT-PYTHON-PR-PREVIEW.yaml",
    template: PR_PREVIEW,
    vars: {
      TYPE_UPPER: "PYTHON",
      SUFFIX: "python",
      INTERNAL_PORT: "8000",
      HEADER_TITLE: [
        "# Python/FastAPI PR Preview (SSH + Docker + Traefik)",
        "# Manages the preview environment automatically through PR or issue comment commands.",
        "# Routing is dynamic via the Traefik reverse proxy.",
      ],
      HEADER_SECRETS: [
        "# DOCKERHUB_USERNAME: Docker Hub username",
        "# DOCKERHUB_TOKEN: Docker Hub access token",
        "# SERVER_HOST: server host (SSH address)",
        "# SERVER_USER: SSH username",
      ],
      SETTINGS_TITLE: ["# Project settings: when reusing this in another project, edit only this section"],
      HEALTH_BLOCK: [
        "HEALTH_CHECK_PATH: '/docs'",
        "HEALTH_CHECK_LOG_PATTERN: 'Uvicorn running on|Application startup complete'",
        "API_DOCS_PATH: '/docs'",
      ],
      BUILD_FAIL_HINTS: [
        "m('wf_preview.hint_docker_python'),",
        "m('wf_preview.hint_start_python'),",
      ],
      // Comments that exist only for the Go preview: an empty array drops the line
      PR_CHECK_COMMENT: [],
      PARSE_COMMENT: [],
      SHA_COMMENT: [],
      HEALTH_COMMENT: [],
      ENV_OPEN: ["# Create the environment file (project-specific section)"],
      ENV_CLOSE: [],
    },
  },
  {
    out: "payload/workflows/react/PROJECT-REACT-CICD.yaml",
    template: CICD_FRONTEND,
    vars: {
      TYPE_UPPER: "REACT",
      IMAGE_PREFIX: "front-container",
      BUILD_JOB_NAME: "Build React/Next.js application",
      // Whole echo line; the message is resolved on the runner and handed to the remote script (see the template)
      PULL_LINE: [
        "m \"${{ env.PAW_M_cicd_pull_image }}\" image=\"${{ secrets.DOCKERHUB_USERNAME }}/${PROJECT_NAME}-${{ env.DOCKER_IMAGE_PREFIX }}:${BRANCH}\"",
      ],
      HEADER: [
        "# React CI/CD deployment",
        "# Builds a Docker image and deploys it when the {{MAIN_BRANCH}} branch is pushed.",
      ],
      DEPLOY_VARS: [
        "# Branch name passed from GitHub",
        "BRANCH=${{ github.ref_name }}",
        "",
        "# Project settings",
        "PROJECT_NAME=\"${{ env.PROJECT_NAME }}\"",
        "",
        "# Per-branch port and container name",
        "# Defaults",
        "PORT=3000",
        "CONTAINER_NAME=\"${PROJECT_NAME}-front\"",
      ],
      BRANCH_BLOCK: [
        "# Per-branch environment settings",
        "if [ \"$BRANCH\" == \"{{MAIN_BRANCH}}\" ]; then",
        "  # 🚀 Deploy environment ({{MAIN_BRANCH}} branch)",
        "  # Uses the PROJECT_DEPLOY_PORT value from GitHub Secrets",
        "  # Falls back to 3000 when it is not set",
        "  PORT=${{ secrets.PROJECT_DEPLOY_PORT || '3000' }}",
        "  CONTAINER_NAME=\"${PROJECT_NAME}-front-deploy\"",
        "  m \"${{ env.PAW_M_cicd_deploy_start }}\" branch=\"$BRANCH\"",
        "",
        "else",
        "  # Any other branch (unexpected)",
        "  m \"${{ env.PAW_M_cicd_branch_unsupported }}\" branch=\"$BRANCH\"",
        "  m \"${{ env.PAW_M_cicd_branch_only }}\" branch=\"{{MAIN_BRANCH}}\"",
        "  m \"${{ env.PAW_M_cicd_branch_hint }}\"",
        "  exit 1",
        "fi",
      ],
      CONFIG_COMMENT: [
        "# Print the settings",
      ],
      EXISTING_COMMENT: [
        "# Check whether a container with the same name exists",
      ],
      RUN_COMMENT: [],
      RUN_ENV: [],
      RUN_RESTART: [],
      FOOTER: [
        "# Usage example - using the {{MAIN_BRANCH}} branch",
        "#",
        "# Current setup: deploys automatically on push to the {{MAIN_BRANCH}} branch",
        "#",
        "# Port per branch:",
        "# - {{MAIN_BRANCH}}: 3000 (can be changed with the PROJECT_DEPLOY_PORT secret)",
        "#",
        "# Required Secrets:",
        "# - REACT_ENV_FILE, DOCKERHUB_*, SERVER_* (required)",
        "# - PROJECT_DEPLOY_PORT (선택, default: 3000)",
        "#",
        "",
      ],
    },
  },
  {
    out: "payload/workflows/next/PROJECT-NEXT-CICD.yaml",
    template: CICD_FRONTEND,
    vars: {
      TYPE_UPPER: "NEXT",
      IMAGE_PREFIX: "nextjs-container",
      BUILD_JOB_NAME: "Build Next.js application",
      PULL_LINE: [
        "m \"${{ env.PAW_M_cicd_pull_image_short }}\"",
      ],
      HEADER: [
        "# Next.js CI/CD deployment",
        "# Builds a Docker image and deploys it when the {{MAIN_BRANCH}} branch is pushed. Deployed as a Node.js runtime container to support SSR.",
      ],
      DEPLOY_VARS: [
        "BRANCH=${{ github.ref_name }}",
        "PROJECT_NAME=\"${{ env.PROJECT_NAME }}\"",
        "",
        "# Per-branch port and container name",
        "PORT=3000",
        "CONTAINER_NAME=\"${PROJECT_NAME}-nextjs\"",
      ],
      BRANCH_BLOCK: [
        "if [ \"$BRANCH\" == \"{{MAIN_BRANCH}}\" ]; then",
        "  PORT=${{ secrets.PROJECT_DEPLOY_PORT || '3000' }}",
        "  CONTAINER_NAME=\"${PROJECT_NAME}-nextjs-deploy\"",
        "  m \"${{ env.PAW_M_cicd_deploy_start }}\" branch=\"$BRANCH\"",
        "else",
        "  m \"${{ env.PAW_M_cicd_branch_unsupported }}\" branch=\"$BRANCH\"",
        "  exit 1",
        "fi",
      ],
      CONFIG_COMMENT: [],
      EXISTING_COMMENT: [],
      RUN_COMMENT: [
        "# Next.js needs a Node.js server for SSR",
        "# With standalone mode, run it with node server.js",
      ],
      RUN_ENV: [
        "-e NODE_ENV=production \\",
      ],
      RUN_RESTART: [
        "--restart unless-stopped \\",
      ],
      FOOTER: [
        "# Next.js Dockerfile example (standalone mode)",
        "#",
        "# # Stage 1: Dependencies",
        "# FROM node:20-alpine AS deps",
        "# WORKDIR /app",
        "# COPY package*.json ./",
        "# RUN npm ci --only=production",
        "#",
        "# # Stage 2: Builder",
        "# FROM node:20-alpine AS builder",
        "# WORKDIR /app",
        "# COPY --from=deps /app/node_modules ./node_modules",
        "# COPY . .",
        "# RUN npm run build",
        "#",
        "# # Stage 3: Runner",
        "# FROM node:20-alpine AS runner",
        "# WORKDIR /app",
        "# ENV NODE_ENV production",
        "#",
        "# RUN addgroup --system --gid 1001 nodejs",
        "# RUN adduser --system --uid 1001 nextjs",
        "#",
        "# COPY --from=builder /app/public ./public",
        "# COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./",
        "# COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static",
        "#",
        "# USER nextjs",
        "# EXPOSE 3000",
        "# ENV PORT 3000",
        "# CMD [\"node\", \"server.js\"]",
        "#",
        "# Add the standalone setting to next.config.js:",
        "# module.exports = {",
        "#   output: 'standalone',",
        "# }",
      ],
    },
  },
  {
    out: "payload/workflows/go/PROJECT-GO-SIMPLE-CICD.yaml",
    template: SIMPLE_CICD,
    vars: {
      TYPE_UPPER: "GO",
      SUFFIX: "go",
      DEPLOY_PORT_DEFAULT: "8080",
      HEADER_TITLE: ["# Go CI/CD deployment (SSH + Docker)"],
      HEADER_SECRETS: [
        "# DOCKERHUB_USERNAME / DOCKERHUB_TOKEN: DockerHub username / access token",
        "# SERVER_HOST / SERVER_USER: deploy server address / SSH username",
      ],
      HEADER_ENV: [
        "# Environment variables (set in the env section)",
        "# CONTAINER_INTERNAL_PORT: Go app internal port (default: 8080) / DEPLOY_PORT: deploy port",
        "# CONTAINER_NAME: container name (default: PROJECT_NAME)",
        "# ENABLE_VOLUME_MOUNT (true/false), VOLUME_HOST_PATH, VOLUME_CONTAINER_PATH: volume mount",
        "# SSH_PORT (default: 2022), SSH_COMMAND_TIMEOUT (default: 600s), SSH_CONNECTION_TIMEOUT (default: 60s)",
        "# HEALTHCHECK_WAIT_SECONDS: initialization wait time (default: 10s)",
        "# HEALTHCHECK_PATH: HTTP endpoint path (only logs are used when empty, e.g. \"/health\", \"/api/v1/health\")",
        "# HEALTHCHECK_MAX_RETRIES: HTTP retry count (default: 5) / HEALTHCHECK_RETRY_INTERVAL: retry interval (default: 3s)",
        "# HEALTHCHECK_LOG_PATTERN: fallback log search pattern",
      ],
      PORT_COMMENT: [],
      SSH_COMMENT: [],
      CONTAINER_PORT_BLOCK: ["CONTAINER_INTERNAL_PORT: \"8080\"  # Go app internal port"],
      HEALTH_PATH: "/health",
      HEALTH_LOG_LINE: [
        "HEALTHCHECK_LOG_PATTERN: \"listening on\"  # Fallback log search pattern (adjust to your project's log wording)",
      ],
      BUILD_JOB_NAME: "Build Go application",
      PULL_SUFFIX: "",
      RUN_DOC: [
        "# - Port mapping: ${PORT}:${{ env.CONTAINER_INTERNAL_PORT }} (external:internal)",
        "# - Time zone: Asia/Seoul",
        "# - Volume mount: local time sync and project data",
      ],
      VOLUME_COMMENT: ["# Build the volume mount options"],
      DONE_COMMENT: ["# Confirm the deployment"],
      URL_SUFFIX: "",
    },
  },
  {
    out: "payload/workflows/python/PROJECT-PYTHON-SIMPLE-CICD.yaml",
    template: SIMPLE_CICD,
    vars: {
      TYPE_UPPER: "PYTHON",
      SUFFIX: "python",
      DEPLOY_PORT_DEFAULT: "8000",
      HEADER_TITLE: ["# Python FastAPI CI/CD deployment (SSH + Docker)"],
      HEADER_SECRETS: [
        "# DOCKERHUB_USERNAME: DockerHub username",
        "# DOCKERHUB_TOKEN: DockerHub access token",
        "# SERVER_HOST: deploy server address",
        "# SERVER_USER: SSH username",
      ],
      HEADER_ENV: [
        "# Environment variables are set in the env section below; each line has its description and default.",
        "# HEALTHCHECK_PATH examples: FastAPI \"/docs\", custom \"/api/v1/health\"",
      ],
      PORT_COMMENT: ["# Port settings"],
      SSH_COMMENT: ["# SSH connection settings"],
      CONTAINER_PORT_BLOCK: [
        "# Container port settings",
        "CONTAINER_INTERNAL_PORT: \"8000\"  # FastAPI internal port",
      ],
      HEALTH_PATH: "/docs",
      HEALTH_LOG_LINE: ["HEALTHCHECK_LOG_PATTERN: \"Uvicorn running on\"  # Fallback log search pattern"],
      BUILD_JOB_NAME: "Build Python FastAPI application",
      PULL_SUFFIX: "",
      // No guide comments on the Python side, so an empty array removes the line itself
      RUN_DOC: [],
      VOLUME_COMMENT: [],
      DONE_COMMENT: [],
      URL_SUFFIX: "/docs",
    },
  },
];
